### ISSUE TITLE
Add support for getting raw pixels

### ISSUE THREAD

**Issue by styfle** [Brooooooklyn/Image#24]
As the inverse of #8, it would be nice to get the raw pixels of an image for the purpose of detecting a color pallet.

For example, perhaps a new method, `getImageData()`, which is how it would be solved with `<canvas>`:

```ts
import { readFileSync } from 'fs'
import palette = from 'get-rgba-palette'
import { Image } from '@napi-rs/image'

const decoder = new Transformer(readFileSync('./img.jpg'))
const pixels = decoder.getImageData()
const colors = palette(pixels, 5)
```

https://github.com/mattdesl/get-rgba-palette

**Comment by Brooooooklyn** [comment]
Supported in https://github.com/Brooooooklyn/Image/pull/19
