### ISSUE TITLE
[Bug] Transformer.fromRgbaPixels error

### ISSUE THREAD

**Issue by subframe7536** [Brooooooklyn/Image#48]
### Search before asking

- [X] I searched in the [issues](https://github.com/Brooooooklyn/Image/issues) and found nothing similar.

### Image version

1.6.0

### System version

Windows 11

### Node.js version

16.15.0

### Minimal reproduce step

```js
import { decode, encode } from "blurhash"
import { Transformer, ResizeFit, FastResizeFilter } from "@napi-rs/image"

const img = new Transformer(sourceCover)
  .fastResize({
    width: size,
    height: size,
    filter: FastResizeFilter.Mitchell,
    fit: ResizeFit.Inside,
  })
img.jpegSync(quality)

const { width, height } = await img.metadata()
const rawPixels = Uint8ClampedArray.from(img.rawPixelsSync())
const hash = encode(rawPixels, width, height, 4, 4)

console.log(hash) // UXON5qkC_Nt7IBofxuae?vt7MyRj%2f6bHR*

const decoded = decode(hash, width, height)
const blurBuffer = Transformer.fromRgbaPixels(decoded).rawPixelsSync()

console.log(blurBuffer.length)
```

### What did you expect to see?

pixels length

### What did you see instead?

```
const blurBuffer = Transformer.fromRgbaPixels(decoded).rawPixelsSync()
                               ^

Error: Failed to convert napi value Undefined into rust type `u32`
    at file:///D:/code/Front/electron/node-test/index.js:113:32 {
  code: 'NumberExpected'
}
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Brooooooklyn** [comment]
> `const blurBuffer = Transformer.fromRgbaPixels(decoded).rawPixelsSync()`

`static fromRgbaPixels(input: Uint8Array | Uint8ClampedArray, width: number, height: number): Transformer`

Width and Height is required.
